export { default as Navigation } from './navigation';
export { default as Hero } from './hero';
export { default as About } from './about';
export { default as Skills } from './skills';
export { default as Achievements } from './achievements';
export { default as Projects } from './projects';
export { default as Contact } from './contact';
export { default as Footer } from './footer';
export { default as Gallery } from './gallery';
