
import { ArrowRight, Check, ChevronsUpDown, Circle, Copy, Edit, File, HelpCircle, Home, Loader2, Mail, MessageSquare, Moon, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, Sun, Trash, User, X, Workflow, Instagram, Github, Linkedin, MessageCircle, School2, Calendar, Book, MapPin, ExternalLink } from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  school: School2,
  messageCircle: MessageCircle,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
   instagram: Instagram,
  calendar: Calendar,
  book: Book,
  mapPin: MapPin,
  github: Github,
  linkedin: Linkedin,
};

export {Icons};
